import { hashCurriculumPackage } from "./package";
import type { CanonicalCurriculumPackage } from "./types";

const DOLLAR_TAG = "$focus_curriculum_package$";

/**
 * Diff-friendly JSON: one node or edge per line, stable key order. The value
 * is identical to JSON.stringify(pkg) once parsed.
 */
export function formatCurriculumPackageJson(pkg: CanonicalCurriculumPackage) {
  const lines = [
    `{"formatVersion":${JSON.stringify(pkg.formatVersion)},`,
    `"source":${JSON.stringify(pkg.source)},`,
    `"nodes":[`,
    pkg.nodes.map((node) => JSON.stringify(node)).join(",\n"),
    `],`,
    `"edges":[`,
    pkg.edges.map((edge) => JSON.stringify(edge)).join(",\n"),
    `]}`,
  ];
  return lines.filter((line) => line !== "").join("\n");
}

/**
 * Renders a Supabase migration that imports the package through
 * public.focus_import_curriculum. The function validates everything again,
 * runs in the migration transaction and aborts it on any inconsistency.
 */
export function renderCurriculumImportMigration(
  pkg: CanonicalCurriculumPackage,
  options: { allowMassDeactivation?: boolean; generatedBy?: string } = {},
) {
  const json = formatCurriculumPackageJson(pkg);
  if (json.includes(DOLLAR_TAG))
    throw new Error("Le paquet contient le délimiteur SQL réservé.");
  const comment = (value: string) => value.replace(/[\r\n]+/g, " ");
  return [
    `-- Curriculum import generated by ${comment(options.generatedBy ?? "scripts/curriculum.ts")} — do not edit by hand.`,
    `-- Source: ${comment(pkg.source.officialReference)} (${comment(pkg.source.subjectCode)} / ${comment(pkg.source.levelCode)} / ${comment(pkg.source.schoolYear)})`,
    `-- URL: ${comment(pkg.source.sourceUrl)}`,
    `-- Package hash: ${hashCurriculumPackage(pkg)}`,
    `-- ${pkg.nodes.length} nodes, ${pkg.edges.length} relationships.`,
    `-- Idempotent: re-running it on an up-to-date database changes nothing.`,
    `select public.focus_import_curriculum(`,
    `${DOLLAR_TAG}${json}${DOLLAR_TAG}::jsonb,`,
    `  false, -- p_dry_run`,
    `  ${options.allowMassDeactivation ? "true" : "false"} -- p_allow_mass_deactivation`,
    `);`,
    ``,
  ].join("\n");
}
